[project]
name = "saga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "pendulum>=3.1.0",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.45",
]
